# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: ETHOS
author: Tethix
email: ethos@tethix.co
description: >- # this means to ignore newlines until "baseurl:"
  ETHOS is your responsible tech journey companion. Explore Elemental Sparks, the Seed Catalog, and Tools Directory to inspire discussion, reflection, and practice. 
baseurl: "/ethos-jekyll" # the subpath of your site, e.g. /blog
url: "https://tethix-ethos.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate-v2
  - jekyll-target-blank

# Collections
collections:
  sparks:
    output: true
    permalink: /sparks/:title/
    sort_by: title
  seeds:
    output: true
    permalink: /seed-catalog/:title/
    sort_by: date, title
  tools:
    output: true
    permalink: /tools/:title/
    sort_by: date, title

# Front Matter Defaults
defaults:
  - scope:
      path: ""
    values:
      image: /assets/img/tethix-ethos-feature-img.png
  - scope:
      path: ""
      type: "sparks"
    values:
      layout: "spark"
  - scope:
      path: ""
      type: "seeds"
    values:
      layout: "seed"
  - scope:
      path: ""
      type: "tools"
    values:
      layout: "tool"

# Settings for jekyll-paginate-v2 plugin
# https://github.com/sverrirs/jekyll-paginate-v2/blob/master/README-GENERATOR.md
pagination:  
  enabled: true
  collection: sparks, seeds, tools
  per_page: 12
  sort_reverse: true
  permalink: '/page/:num/'

autopages:
  enabled: false

# Feed settings
feed:
  collections:
    sparks:
      path: "/sparks.xml"
    seeds:
      path: "/seeds.xml"
    tools:
      path: "/tools.xml"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
